openapi: 3.0.0
info:
  version: '1.0'
  title: 'Mushroom_ML'
  description: 'API for Machine Learning application'
paths: 
  /file/{filename}:
    post:
      tags:
        - Upload
      summary: upload instances of data to be predicted
      operationId: file.upload
      parameters:
              - name: filename
                in: path
                description:  file upload
                required: true
                schema:
                  type: string
            
      responses:
        '405':
         description: Invalid input
         # '201':
         #description: 'Upload success'
      requestBody:
        content:
         multipart/form-data:
           schema:
              type: object
              properties:
               file:
                 type: string
                 format: binary
    get:
      tags:
        - Download
      summary: Download a file
      operationId: file.download
      parameters:
              - name: filename
                in: path
                description:  file upload
                required: true
                schema:
                  type: string
      responses:
        '405':
          description: Invalid input
          
          # delete:
          #  tags:
          # - Remove
          # summary: Remove a file 
          #  operationId: file.remove
          # responses:
          # '405':
          # description: 'Invalid Input or Non-removable file'
  /list:
    get:
      tags:
        - List
      operationId: file.list_files
      description: Returns cpu information of the hosting server
      responses:
        '200':
          description: 'CPU info, or add more text'

  /predict/{filename}:
    get:
      tags:
        - Predict
      operationId: prediction.predict
      description: get ML prediction for file input
      parameters:
              - name: filename
                in: path
                description:  name of uploaded file
                required: true
                schema:
                  type: string
      responses:
        '405':
          description: Invalid input
           
  /predict_path:
    get:
      tags:
        - Image
      operationId: model.image
      description: get model decision tree with highlighted path
      responses:
        '200':
          description: 'No recent predictions'
  /model:
    get:
      tags:
        - Image
      summary: list of links to model evaluation options
      operationId: mush_model.model
      responses:
        '300':
          description: 'Choose one of the evaluation options'
  /confusion_matrix:
    get:
      tags:
        - Text
      summary: confusion matrix of training
      operationId: mush_model.confusion_matrix
      responses:
        '200':
          description: 'Confusion Matrix'
  /assessment:
    get:
      tags:
        - Text
      operationId: mush_model.evaluation
      description: get Precision, Recall, F1, Accuracy
      responses:
        '200':
          description: 'Assessment Calculations'
        
servers:
        # Added by API Auto Mocking Plugin
        - description: SwaggerHub API Auto Mocking
          url: https://virtserver.swaggerhub.com/E222-SP21/Mushroom_ML.yaml/1.0
        - url: 'http://localhost:8080/'