# -*- coding: utf-8 -*-
"""mush_model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_1eyW3-6GbB3B8zXXgnXRVnDSyGCe7pR
"""

import numpy as np
import os
from sklearn import preprocessing
from flask import json, jsonify, request, redirect, url_for, make_response
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import imageio
import io as StringIO
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas


UPLOAD_FOLDER='.'
filename = "mushrooms.csv"
file_path = os.path.join(UPLOAD_FOLDER, filename)
data = pd.read_csv(file_path)

le = LabelEncoder()

for i in data.columns:
    data[i] = le.fit_transform(data[i])

y = data["class"]
x = data.drop(["class","gill-attachment","bruises"], axis = 1)

xv = x.values
yv = y.values

x_train, x_test, y_train, y_test = train_test_split(xv, yv, test_size=0.8, random_state=2019)

my_tree = DecisionTreeClassifier(max_depth = 100)
fig = my_tree.fit(x_train,y_train)

prediction = fig.predict(x_test)


def README():
 
    message_4  = ["Use endpoints /predict-csv/{filename} for csv files or /predict_input/{inputs} for manual input."]
    message_4.append("The csv file should have headers and be formatted like mushrooms.csv without the class, which will be predicted.")
    message_4.append("Both should be in the following encode:")
    message_4.append("cap-shape: bell=b,conical=c,convex=x,flat=f, knobbed=k,sunken=s")
    message_4.append("cap-surface: fibrous=f,grooves=g,scaly=y,smooth=s ")
    message_4.append("cap-color: brown=n,buff=b,cinnamon=c,gray=g,green=r,pink=p,purple=u,red=e,white=w,yellow=y")
    message_4.append("bruises: bruises=t,no=f")
    message_4.append("odor: almond=a,anise=l,creosote=c,fishy=y,foul=f,musty=m,none=n,pungent=p,spicy=s")
    message_4.append("gill-attachment: attached=a,descending=d,free=f,notched=n")
    message_4.append("gill-spacing: close=c,crowded=w,distant=d")
    message_4.append("gill-size: broad=b,narrow=n")
    message_4.append("gill-color: black=k,brown=n,buff=b,chocolate=h,gray=g, green=r,orange=o,pink=p,purple=u,red=e,white=w,yellow=y")
    message_4.append("stalk-shape: enlarging=e,tapering=t")
    message_4.append("stalk-root: bulbous=b,club=c,cup=u,equal=e,rhizomorphs=z,rooted=r,missing=?")
    message_4.append("stalk-surface-above-ring: fibrous=f,scaly=y,silky=k,smooth=s")
    message_4.append("stalk-surface-below-ring: fibrous=f,scaly=y,silky=k,smooth=s")
    message_4.append("stalk-color-above-ring: brown=n,buff=b,cinnamon=c,gray=g,orange=o,pink=p,red=e,white=w,yellow=y")
    message_4.append("stalk-color-below-ring: brown=n,buff=b,cinnamon=c,gray=g,orange=o,pink=p,red=e,white=w,yellow=y")
    message_4.append("veil-type: partial=p,universal=u")
    message_4.append("veil-color: brown=n,orange=o,white=w,yellow=y")
    message_4.append("ring-number: none=n,one=o,two=t")
    message_4.append("ring-type: cobwebby=c,evanescent=e,flaring=f,large=l,none=n,pendant=p,sheathing=s,zone=z")
    message_4.append("spore-print-color: black=k,brown=n,buff=b,chocolate=h,green=r,orange=o,purple=u,white=w,yellow=y")
    message_4.append("population: abundant=a,clustered=c,numerous=n,scattered=s,several=v,solitary=y")
    message_4.append("habitat: grasses=g,leaves=l,meadows=m,paths=p,urban=u,waste=w,woods=d")
    return jsonify(message_4)

def tree():
    filename = "fig1.jpg"
    file_path = os.path.join(UPLOAD_FOLDER, filename)
    fig = imageio.imread(file_path)
    axis = fig.add_subplot(1, 1, 1)

    axis.imshow(fig)
    canvas = FigureCanvas(fig)
    output = StringIO.StringIO()
    canvas.print_png(output)
    response = make_response(output.getvalue())
    response.mimetype = 'image/png'
    return response
    

def confusionMatrix():
    
    [TP, TN, FP, FN] = confusion_matrix(y_test, prediction, labels = [1,0]).ravel()
    matrix = ["             Actual"]
    matrix.append("m         True | False")
    string1 = "o True ["+str(TP) +" | "+str(FP) + "]"
    matrix.append(string1)
    matrix.append("d      [--------------]")
    string2  = "e False[" + str(TN)+ "  | " + str(FN) + "]"
    matrix.append(string2)
    matrix.append("l")
    return jsonify(matrix)

def evaluation():
    [TP, TN, FP, FN] = confusion_matrix(y_test, prediction, labels = [1,0]).ravel()
    evalu = ["Accuracy"]
    evalu.append((TP+TN)/(TP+TN+FP+FN))
    evalu.append("Precision")
    evalu.append(TP/(TP+FP))
    evalu.append("Recall")
    evalu.append(TP/(TP+FN))
    evalu.append("F1 Score")
    evalu.append(2*TP/(2*(TP+FN+FP)))
    return jsonify(evalu)

