openapi: 3.0.0
info:
  version: '1.0'
  title: 'Mushroom_ML'
  description: 'API for Machine Learning application'
paths: 
  /file/{filename}:
    post:
      tags:
        - Upload
      summary: upload instances of data to be predicted
      operationId: file.upload
      parameters:
              - name: filename
                in: path
                description:  file upload
                required: true
                schema:
                  type: string
            
      responses:
        '405':
         description: Invalid input
         # '201':
         #description: 'Upload success'
      requestBody:
        content:
         multipart/form-data:
           schema:
              type: object
              properties:
               file:
                 type: string
                 format: binary
    get:
      tags:
       - Download
      summary: Download a file
      operationId: file.download
      parameters:
              - name: filename
                in: path
                description:  file name to download
                required: true
                schema:
                 type: string
      responses:
       '405':
         description: Invalid input
          
          # delete:
          #  tags:
          # - Remove
          # summary: Remove a file 
          #  operationId: file.remove
          # responses:
          # '405':
          # description: 'Invalid Input or Non-removable file'
  /list:
    get:
      tags:
       - List
      operationId: file.list_files
      description: Returns cpu information of the hosting server
      responses:
        '200':
          description: 'CPU info, or add more text'

  /predict_csv/{filename}:
    get:
      tags:
        - Predict
      operationId: prediction.predict_csv
      description: get ML prediction for file input
      parameters:
              - name: filename
                in: path
                description:  name of uploaded file
                required: true
                schema:
                  type: string
      responses:
        '405':
          description: Invalid input
           
  /READ_ME:
    get:
      tags:
        - Text
      operationId: mush_model.README
      description: read to understand more about model
      responses:
        '200':
          description: 'No recent predictions'
#  /tree:
#     get:
#      tags:
#        - Image
#      summary: list of links to model evaluation options
#      operationId: mush_model.tree
#      responses:
#        '300':
#          description: 'Choose one of the evaluation options'
  /confusionMatrix:
     get:
      tags:
        - Text
      summary: confusion matrix of training
      operationId: mush_model.confusionMatrix
      responses:
        '200':
          description: 'Confusion Matrix'
  /assessment:
    get:
      tags:
        - Text
      operationId: mush_model.evaluation
      description: get Precision, Recall, F1, Accuracy
      responses:
        '200':
          description: 'Assessment Calculations'
       
servers:
        - url: 'http://localhost:8080/'
