openapi: 3.0.0
info:
  version: '1.0'
  title: 'Mushroom_ML'
  description: 'API for Machine Learning application'
paths: 
  /file/<filename>:
    post:
      tags:
        -Upload
      summary: upload instances of data to be predicted
      operationID: file.upload
      parameters:
        name: filename
        in: query
        description:  file upload
        required: true
        schema:
          type: string
            
      responses:
        '405':
          description: Invalid input
        '201':
          description: 'Upload success'
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
    get:
      tags:
        - Download
      summary: Download a file
      operationId: file.download
      responses:
        '405':
          description: Invalid input
    delete:
      tags:
        - Remove
      summary: Remove a file 
      operationId: file.remove
      responses:
        '405':
          description: Invalid Input or Non-removable file
  /list:
    get:
      tags:
        - List
      operationId: file.list_files
      description: Returns cpu information of the hosting server
      responses:
        '200':
          description: 'CPU info, or add more text'

  /predict/<filename>:
    get:
      tags:
        - Predict
      operationId: file.predict
      description: get ML prediction for file input
      responses:
        '405':
          description: Invalid input
           
  /predict/path:
    get:
      tags:
        - Image
      operationId: model.image
      description: get model decision tree with highlighted path
      responses:
        '200':
          description: 'No recent predictions'
  /model:
    get:
      tags:
        - List
      summary: list of model evaluation options
      operationId: model.list
      responses:
        '300':
          description: 'Choose one of the evaluation options'
  /model/confusion_matrix:
    get:
      tags:
        - Text
      summary: confusion matrix of training
      operationId: model.confusion_matrix
      responses:
        '200':
          description: 'Confusion Matrix'
  /model/ROC:
    get:
      tags:
        - Image
      operationId: model.ROC
      description: get ROC curve of model
      responses:
        '200':
          description: 'ROC curve'
  /model/evaluation:
    get:
      tags:
        - Text
      operationId: model.evaluation
      description: get Precision, Recall, F1, Accuracy
      responses:
        '200':
          description: 'Assessment Calculations'
  /model/evaluation/download:
    get:
      tags:
        - Download
      summary: Download a formatted evaluation summary file
      operationId: model.download
      responses:
        '500':
          description: Internal Server Error
  /model/evaluation/history:
    get:
      tags:
        - Download
        - List
      summary: List of previous evaluation summary files
      operationId: model.history
      responses:
        '200':
          description: 'Model Evaluation History'
        
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/E222-SP21/Mushroom_ML.yaml/1.0